# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hi, It's Me! Irina Lu
subtitle: This's Irina Lu
description: Wenjia's Tech Blog
keywords:
author: wenjia lu
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
#url: http://example.com
url: https://wenjialu.github.io/hexo_blog/
root: /hexo_blog/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: src
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
    - "cv/**" 
    - "projects/**" 


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: true
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
# Include/Exclude Files/Folders
include:
exclude:
## Exclude example code from Nunjucks
  - "v2/examples/vue-20-*/*"
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: red
# theme: hexo-theme-space-cadet
# theme: hexo-matery-modified-master


# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: https://github.com/wenjialu/hexo_blog
  branch: master

# animate
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  log: false
  model:
    use: live2d-widget-model-shizuku
  display:
    position: right
    width: 150
    height: 300
  mobile:
    show: true
  react:
    opacity: 0.7

# vue
alias:
  api/index.html: v2/api/index.html
  guide/class-and-style.html: v2/guide/class-and-style.html
  guide/comparison.html: v2/guide/comparison.html
  guide/components.html: v2/guide/components.html
  guide/computed.html: v2/guide/computed.html
  guide/conditional.html: v2/guide/conditional.html
  guide/custom-directive.html: v2/guide/custom-directive.html
  guide/deployment.html: v2/guide/deployment.html
  guide/events.html: v2/guide/events.html
  guide/forms.html: v2/guide/forms.html
  guide/index.html: v2/guide/index.html
  guide/installation.html: v2/guide/installation.html
  guide/instance.html: v2/guide/instance.html
  guide/join.html: v2/guide/join.html
  guide/list.html: v2/guide/list.html
  guide/migration-vue-router.html: v2/guide/migration-vue-router.html
  guide/migration-vuex.html: v2/guide/migration-vuex.html
  guide/migration.html: v2/guide/migration.html
  guide/mixins.html: v2/guide/mixins.html
  guide/plugins.html: v2/guide/plugins.html
  guide/reactivity.html: v2/guide/reactivity.html
  guide/render-function.html: v2/guide/render-function.html
  guide/routing.html: v2/guide/routing.html
  guide/single-file-components.html: v2/guide/single-file-components.html
  guide/ssr.html: v2/guide/ssr.html
  guide/state-management.html: v2/guide/state-management.html
  guide/syntax.html: v2/guide/syntax.html
  guide/transitioning-state.html: v2/guide/transitioning-state.html
  guide/transitions.html: v2/guide/transitions.html
  guide/unit-testing.html: v2/guide/unit-testing.html
  examples/commits.html: v2/examples/commits.html
  examples/elastic-header.html: v2/examples/elastic-header.html
  examples/firebase.html: v2/examples/firebase.html
  examples/grid-component.html: v2/examples/grid-component.html
  examples/hackernews.html: v2/examples/hackernews.html
  examples/index.html: v2/examples/index.html
  examples/modal.html: v2/examples/modal.html
  examples/select2.html: v2/examples/select2.html
  examples/svg.html: v2/examples/svg.html
  examples/todomvc.html: v2/examples/todomvc.html
  examples/tree-view.html: v2/examples/tree-view.html