
# html lang
language: zh-cmn-Hans

# main menu navigation，顶部导航栏链接
menu:
  Home: /
  Archives: /blog/archives
  About: /about

excerpt: true

# feed
atom: /atom.xml

# Miscelaneous
favicon: /img/favicon.png

# 百度统计，你可以在根目录的_config.yml中添加baidu_tongji_id
baidu_tongji_id: 

# uyan 评论系统，你可以在根目录的_config.yml中添加uyan_id
uyan_id: 
